[package]
name = "hnefatafl"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.13.2"
macros = { path = "macros" }

[dev-dependencies]
bevy-inspector-egui = "0.24.0"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
